# Generated by Django 5.2.7 on 2025-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_abstractuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
