# Generated by Django 5.2.7 on 2025-10-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('product', models.ManyToManyField(related_name='tags', to='Store.product')),
            ],
        ),
    ]
